language: React_js
React_js:
  - 'stable'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
git:
  depth: 3
script:
  - npm run build

deploy:
  provider: pages
  name: Ait tghrayt youssef
  email: Tghrayt.ysf@gmail.com
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
